---
- name: Install FTP service
  hosts: ftp_mirror
  become: True
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: True
        pkg:
          - ftp

- name: Configure FTP service 
  hosts: ftp_mirror
  become: True
  tasks:
    - name: Install vsftp
      apt:
        name: vsftp
        state: present