---
- name: Install FTP service
  hosts: ftp_mirror
  become: True
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: True
        pkg:
          - ftp

- name: Configure FTP service 
  hosts: ftp_mirror
  become: True
  tasks:
    - name: Install vsftpd
      apt:
        name: vsftpd
        state: present
    - name: Copy vsftpd.conf
      copy:
        src: vsftpd.conf
        dest: /etc/vsftpd.conf