---
- name: Install FTP service
  hosts: ftp
  become: True
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: True
        pkg:
          - ftp

- name: Configure FTP service anonymous
  hosts: ftp
  become: True
  tasks:
    - name: Install vsftp
      apt:
        name: vsftp
        state: present