---
- name: Install FTP service
  hosts: ftp
  become: True
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: True
        pkg:
          - ftp

- name: Configure FTP service anonymous
  hosts: ftp
  become: True
  tasks:
    - name: Install vsftp
      apt:
        name: vsftp
        state: present
    
    - name: Configure vsftpd for anonymous access
      copy:
        dest: /etc/vsftpd.conf
        content: |
          anonymous_enable=YES
          local_enable=NO
          write_enable=NO
          idle_session_timeout=30
          anon_max_rate=5000
          ftpd_banner=Welcome to SRI FTP anonymous server
          banner_file=/srv/ftp/banner.txt