- name: Set up DNS for the dns.sri.ies
  hosts: dns
  become: True
  tasks: 
    - name: Install bind9
      apt:
        name: 
        - bind9
        - bind9utils
        - bind9-doc
        update_cache: yes


    - name: Copy the DNS config
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      
      loop: 
        - { src: "dns/named.conf.local", dest: "/etc/bind/" }
        - { src: "dns/named.conf.options", dest: "/etc/bind/" }
        - { src: "dns/dbs.sri.ies", dest: "/var/lib/bind" }
        - { src: "dns/named", dest: "/etc/defaults/" }
      
    - name: Restart bind9
      service:
        name: bind9
        state: restarted