---
- name: Configure FTP service
  hosts: ftp_servers
  become: true
  tasks:
    - name: Install vsftpd package
      ansible.builtin.apt:
        name: vsftpd
        state: present
        update_cache: true

- name: Configure FTP service in ftp server
  hosts: ftp
  become: true
  tasks:
    - name: Copy ftp.vsftpd configuration file
      ansible.builtin.copy:
        src: /files/ftp/ftp.vsftpd.conf
        dest: /etc/vsftpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Ensure ftp user exists
      ansible.builtin.user:
        name: ftp
        shell: /usr/sbin/nologin
        state: present

    - name: Create anonymous FTP root directory
      ansible.builtin.file:
        path: /srv/ftp
        state: directory
        owner: root
        group: root
        mode: '0644'

    - name: Copy banner file
      ansible.builtin.copy:
        src: /vagrant/files/ftp/provisional2_message.txt
        dest: /etc/vsftpd.banner
        owner: root
        group: root
        mode: '0644'

    - name: Copy the resolv.conf
      ansible.builtin.copy:
        src: "../resolv.conf"
        dest: /etc/
        owner: root
        group: root
        mode: '0644'

- name: Configure FTP service in mirror server
  hosts: mirror
  become: true
  vars:
    charles_password: "{{ '1234' | password_hash('sha512') }}"
    laura_password: "{{ '1234' | password_hash('sha512') }}"
  tasks:
    - name: Copy ftp.vsftpd configuration file
      ansible.builtin.copy:
        src: /vagrant/files/ftp/mirror.vsftpd.conf
        dest: /etc/vsftpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy chroot_list for mirror
      ansible.builtin.copy:
        src: /vagrant/files/ftp/vsftpd.chroot_list
        dest: /etc/vsftpd.chroot_list
        owner: root
        group: root
        mode: '0644'

    - name: Create users for mirror
      block:
        - name: Create user charles
          ansible.builtin.user:
            name: charles
            password: "{{ charles_password }}"
            shell: /bin/bash
            state: present

        - name: Create user laura
          ansible.builtin.user:
            name: laura
            password: "{{ laura_password }}"
            shell: /bin/bash
            state: present

        - name: Create home directory for charles
          ansible.builtin.file:
            path: /home/charles/ftp
            state: directory
            owner: charles
            group: charles
            mode: '0755'

        - name: Create home directory for laura
          ansible.builtin.file:
            path: /home/laura/ftp
            state: directory
            owner: laura
            group: laura
            mode: '0755'

        - name: Install dependencies to obtain SSL certificate
          ansible.builtin.package:
            update_cache: true
            name: python3-cryptography

        - name: Generate SSL Private Key
          community.crypto.openssl_privatekey:
            path: "{{ ssl_path }}/ssl-cert-priv.key"
            size: 2048

        - name: Generate sign request (CSR)
          community.crypto.openssl_csr:
            path: "{{ ssl_path }}/ssl-sign.csr"
            privatekey_path: "{{ ssl_path }}/ssl-cert-priv.key"
            common_name: "ssl-ftp-cert"
            country_name: "ES"
            organization_name: "IZV"
            email_address: "team5@ieszaidinvergeles.org"

        - name: Obtain SSL public key
          community.crypto.x509_certificate:
            path: /etc/ssl/certs/ssl-cert-pub.pem
            privatekey_path: "{{ ssl_path }}/ssl-cert-priv.key"
            csr_path: "{{ ssl_path }}/ssl-sign.csr"
            provider: selfsigned

    - name: Copy the resolv.conf
      ansible.builtin.copy:
        src: "../resolv.conf"
        dest: /etc/
        owner: root
        group: root
        mode: '0644'

- name: Restart vsftpd service
  hosts: ftp_servers
  become: true
  tasks:
    - name: Restart vsftpd service
      ansible.builtin.service:
        name: vsftpd
        state: restarted
