- name: Set up DNS for the dns.sri.ies
  hosts: dns
  become: True
  tasks: 
    - name: Install bind9
      apt:
        name: 
          - bind9
          - bind9utils
          - bind9-doc
        update_cache: yes

    - name: Copy the DNS config
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: 
        - { src: "../files/dns/named.conf.local", dest: "/etc/bind/" }
        - { src: "../files/dns/named.conf.options", dest: "/etc/bind/" }
        - { src: "../files/dns/db.sri.ies", dest: "/etc/bind/" }
        - { src: "dns/db.57.168.192", dest: "/etc/bind/" }
        - { src: "../files/dns/named", dest: "/etc/default/" }

    - name: Set permissions for Bind9
      file:
        path: "{{ item }}"
        owner: bind
        group: bind
        mode: '0644'
      loop:
        - /etc/bind/named.conf.local
        - /etc/bind/named.conf.options
        - /etc/bind/db.sri.ies
        - /etc/default/named

    - name: Restart bind9
      service:
        name: bind9
        state: restarted
