- name: Set up DNS for the dns.sri.ies
  hosts: dns
  become: true
  tasks:
    - name: Install bind9
      ansible.builtin.apt:
        name:
          - bind9
          - bind9utils
          - bind9-doc
        update_cache: true

    - name: Copy the DNS config
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: bind
        group: bind
        mode: '0644'
      loop:
        - { src: "{{ dns_path }}/named.conf.local", dest: "/etc/bind/" }
        - { src: "{{ dns_path }}/named.conf.options", dest: "/etc/bind/" }
        - { src: "{{ dns_path }}/db.sri.ies", dest: "/etc/bind/" }
        - { src: "{{ dns_path }}/db.192.168.57", dest: "/etc/bind/" }
        - { src: "{{ dns_path }}/named", dest: "/etc/default/" }

    - name: Set permissions for Bind9
      ansible.builtin.file:
        path: "{{ item }}"
        owner: bind
        group: bind
        mode: '0644'
      loop:
        - { src: "{{ bind_path }}/named.conf.local" }
        - { src: "{{ bind_path }}/named.conf.options" }
        - { src: "{{ bind_path }}/db.sri.ies" }
        - { src: "/etc/default/named" }

    - name: Update serial in db.sri.ies
      ansible.builtin.replace:
        path: /etc/bind/db.sri.ies
        regexp: '(\d+)\s*;\s*Serial'
        replace: "{{ lookup('pipe', 'date +%Y%m%d%H') }} ; Serial"

    - name: Restart Bind9 service
      ansible.builtin.service:
        name: bind9
        state: restarted

    - name: Validate DNS configuration
      ansible.builtin.command: named-checkconf
      register: conf_check
      changed_when: false
      failed_when: conf_check.rc != 0

    - name: Validate zone file
      ansible.builtin.command: named-checkzone sri.ies /etc/bind/db.sri.ies
      register: zone_check
      changed_when: false
      failed_when: zone_check.rc != 0

    - name: Validate Bind9 configuration
      ansible.builtin.command: named-checkconf
      changed_when: false

    - name: Restart bind9
      ansible.builtin.service:
        name: bind9
        state: restarted
