name: ansible-lint
on:
  pull_request:
    branches: ["main"]

# This enables the Run Workflow button on the Actions tab.
workflow_dispatch:

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: "ansible"
          setup_python: "true"
